## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999

script:
  - julia -e 'Pkg.clone(pwd()); ENV["PYTHON"]=""; Pkg.build("ExcelFiles"); Pkg.test("ExcelFiles"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExcelFiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
